task:
  name: Unit Tests
  container:
    image: python:slim
  install_script: |
    python3 -m pip install --upgrade unittest-xml-reporting
    python3 -m pip install .
  script: python3 -m xmlrunner tests
  always:
    unittest_results_artifacts:
      path: ./*.xml
      format: junit
      type: text/xml
